# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: CoopCoins-CoopTokenFees-Indexer
event_decoder: viem

networks:
  - id: 8453
    start_block: 32640102
    contracts:
      - name: CoopCoin
        handler: ./src/EventHandlers.ts
        events:
          - event: CoopTokenFees (address indexed tokenCreator, address indexed platformReferrer, address indexed orderReferrer, address protocolFeeRecipient, uint256 tokenCreatorFee, uint256 platformReferrerFee, uint256 orderReferrerFee, uint256 protocolFee)
            field_selection:
              transaction_fields:
                - hash

unordered_multichain_mode: true
preload_handlers: true
