# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: CoopCoins-CoopTokenFees-Indexer
event_decoder: viem

networks:
  - id: 8453
    start_block: 32640102
    contracts:
      - name: CoopCoin
        handler: ./src/EventHandlers.ts
        abi_file_path: abis/Coop.json
        events:
          - event: CoopTokenFees
            field_selection:
              transaction_fields:
                - hash
          - event: CoopTokenSecondaryRewards
            field_selection:
              transaction_fields:
                - hash

unordered_multichain_mode: true
preload_handlers: true
